--- Schemas/CIM240/CIM_Core.mof.orig	2014-04-23 09:54:36.747533149 -0500
+++ Schemas/CIM240/CIM_Core.mof	2014-04-23 10:57:54.620270955 -0500
@@ -47,6 +47,8 @@
 #pragma include ("DMTF/Core/CIM_ParametersForMethod.mof")
 #pragma include ("DMTF/Core/CIM_ParameterValueSources.mof")
 #pragma include ("DMTF/Core/CIM_PhysicalElement.mof")
+#pragma include ("DMTF/Interop/CIM_Message.mof")
+#pragma include ("DMTF/Interop/CIM_Error.mof")
 #pragma include ("DMTF/Core/CIM_Product.mof")
 #pragma include ("DMTF/Core/CIM_ProductParentChild.mof")
 #pragma include ("DMTF/Core/CIM_ProductPhysicalElements.mof")
@@ -121,6 +123,7 @@
 #pragma include ("DMTF/Core/CIM_ProductPhysicalComponent.mof")
 #pragma include ("DMTF/Core/CIM_ProductSupport.mof")
 #pragma include ("DMTF/Core/CIM_Profile.mof")
+#pragma include ("DMTF/User/CIM_Identity.mof")
 #pragma include ("DMTF/Core/CIM_RedundancyGroup.mof")
 #pragma include ("DMTF/Core/CIM_RedundancySetCapabilities.mof")
 #pragma include ("DMTF/Core/CIM_RedundancySetSettingData.mof")
@@ -147,11 +150,13 @@
 #pragma include ("DMTF/Core/CIM_SpareGroup.mof")
 #pragma include ("DMTF/Core/CIM_StatusCollection.mof")
 #pragma include ("DMTF/Core/CIM_StorageAllocationSettingData.mof")
+#pragma include ("DMTF/User/CIM_StorageHardwareID.mof")
 #pragma include ("DMTF/Core/CIM_StorageHardwareIDElementSettingData.mof")
 #pragma include ("DMTF/Core/CIM_StorageRedundancyGroup.mof")
 #pragma include ("DMTF/Core/CIM_SystemSetting.mof")
 #pragma include ("DMTF/Core/CIM_SystemSettingContext.mof")
 #pragma include ("DMTF/Core/CIM_SystemSpecificCollection.mof")
+#pragma include ("DMTF/System/CIM_VirtualSystemSettingData.mof")
 #pragma include ("DMTF/Core/CIM_VirtualEthernetSwitchSettingData.mof")
 #pragma include ("DMTF/Core/CIM_VirtualSystemManagementCapabilities.mof")
 #pragma include ("DMTF/Core/CIM_VirtualSystemSnapshotCapabilities.mof")
@@ -201,6 +206,10 @@
 #pragma include ("DMTF/Core/CIM_ServiceOption.mof")
 #pragma include ("DMTF/Core/CIM_ServiceSAPDependency.mof")
 #pragma include ("DMTF/Core/CIM_ServiceStatistics.mof")
+#pragma include ("DMTF/User/CIM_SecurityService.mof")
+#pragma include ("DMTF/User/CIM_AuthenticationService.mof")
+#pragma include ("DMTF/User/CIM_IdentityManagementService.mof")
+#pragma include ("DMTF/User/CIM_StorageHardwareIDManagementService.mof")
 #pragma include ("DMTF/Core/CIM_SoftwareInstallationService.mof")
 #pragma include ("DMTF/Core/CIM_TimeService.mof")
 #pragma include ("DMTF/Core/CIM_AllocatedLogicalElement.mof")
@@ -231,6 +240,7 @@
 #pragma include ("DMTF/Core/CIM_AssociatedPowerManagementService.mof")
 #pragma include ("DMTF/Core/CIM_BasedOn.mof")
 #pragma include ("DMTF/Core/CIM_BindsTo.mof")
+#pragma include ("DMTF/System/CIM_ComputerSystem.mof")
 #pragma include ("DMTF/Core/CIM_ComputerSystemElementSettingData.mof")
 #pragma include ("DMTF/Core/CIM_ConfigurationForSystem.mof")
 #pragma include ("DMTF/Core/CIM_ContainedDomain.mof")
@@ -239,6 +249,7 @@
 #pragma include ("DMTF/Core/CIM_DeviceStatistics.mof")
 #pragma include ("DMTF/Core/CIM_DomainMemberCS.mof")
 #pragma include ("DMTF/Core/CIM_ExtentRedundancyComponent.mof")
+#pragma include ("DMTF/Network/CIM_IPProtocolEndpoint.mof")
 #pragma include ("DMTF/Core/CIM_HostedAccessPoint.mof")
 #pragma include ("DMTF/Core/CIM_HostedCollection.mof")
 #pragma include ("DMTF/Core/CIM_HostedIPInterface.mof")
@@ -258,9 +269,14 @@
 #pragma include ("DMTF/Core/CIM_SettingForSystem.mof")
 #pragma include ("DMTF/Core/CIM_StorageHardwareIDManagementServiceDependency.mof")
 #pragma include ("DMTF/Core/CIM_SystemDeviceView.mof")
+#pragma include ("DMTF/Device/CIM_ProtocolController.mof")
+#pragma include ("DMTF/Device/CIM_SCSIProtocolController.mof")
 #pragma include ("DMTF/Core/CIM_SystemSCSIProtocolController.mof")
 #pragma include ("DMTF/Core/CIM_VirtualSystemManagementService.mof")
 #pragma include ("DMTF/Core/CIM_VirtualSystemSnapshotService.mof")
 #pragma include ("DMTF/Core/CIM_AggregatedVirtualSystemManagementService.mof")
+#pragma include ("DMTF/Device/CIM_LogicalPort.mof")
+#pragma include ("DMTF/Device/CIM_NetworkPort.mof")
+#pragma include ("DMTF/Device/CIM_FCPort.mof")
 #pragma include ("DMTF/Core/CIM_SystemFCPort.mof")
  
