# Created by: Bruno Lauze <brunolauze@msn.com>
# $FreeBSD$

PORTNAME=      	openca-tools
PORTVERSION=  	1.3.1
PORTREVISION= 	1
CATEGORIES=     security   
MASTER_SITES=	SF/openca/${PORTNAME}/releases/v${PORTVERSION}/sources/

MAINTAINER=     brunolauze@msn.com
COMMENT=        OpenCA Tools

#BUILD_DEPENDS=	${LOCALBASE}/lib/libssl.so:${PORTDIR}/security/openssl

GNU_CONFIGURE=	yes
USES=         	gmake pkgconfig

NO_STAGE=	yes

.include <bsd.port.mk>
